export const PLUGIN_MANAGER_REQUEST = 'PLUGIN_MANAGER_REQUEST';
export const GET_PLUGINS_SUCCESS = 'GET_PLUGINS_SUCCESS';
export const GET_PLUGINS_ERROR = 'GET_PLUGINS_ERROR';
export const PLUGIN_INSTALL_SUCCESS = 'PLUGIN_INSTALL_SUCCESS';
export const PLUGIN_INSTALL_ERROR = 'PLUGIN_INSTALL_ERROR';
export const PLUGIN_UNINSTALL_ERROR = 'PLUGIN_UNINSTALL_ERROR';
export const PLUGIN_UNINSTALL_SUCCESS = 'PLUGIN_UNINSTALL_SUCCESS';